name: indriver_uber_clone
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  formz: ^0.8.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get_it: ^8.0.3
  google_maps_flutter: ^2.12.3
  google_places_flutter: ^2.1.0
  http: ^1.4.0
  image_picker: ^1.1.2
  mocktail: ^1.0.4
  shared_preferences: ^2.5.3




dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/lottie/

